apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-notes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-notes
  template:
    metadata:
      labels:
        app: django-notes
    spec:
      containers:
        - name: django-notes
          image: django-notes-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          command: ["python"]
          args: ["manage.py", "runserver", "0.0.0.0:8000"]

